### ISSUE TITLE
Dialog Flow redirect link

### ISSUE THREAD

**Issue by AidarBabanov** [dialogflow/dialogflow-java-client-v2#20]
Is it right link (https://login.corp.google.com/request?s=up.corp.google.com:443/uberproxy/aRUEbN7jeIlYqd/&d=https://pantheon.corp.google.com/apis/library/dialogflow.googleapis.com%3Fupxsrf%3DADBfK3aUMXUOYgt1AIYV:1529662534885&maxAge=1200&authLevel=2000000&keyIds=kY-,Q3b,X-q,k02), if I have been redirected from this [page](https://github.com/dialogflow/dialogflow-java-client-v2/tree/master/samples) in setup part? 

Looks like it is corporative service for people working there.

**Comment by nnegrey** [comment]
https://github.com/dialogflow/dialogflow-java-client-v2/pull/21
